swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about Swagger at <a href=\"http://swagger.io\">http://swagger.io</a> or on irc.freenode.net, #swagger.  For this sample, you can use the api key \"special-key\" to test the authorization filters"
  version: 1.0.0
  title: Swagger Predictionstore YAML
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: results
    description: Accessing Predcition Results
    externalDocs:
      description: Find out more
      url: "http://swagger.io"
  - name: user
    description: Access to Predictionstore Users
    externalDocs:
      description: Find out more about our store
      url: "http://swagger.io"
schemes:
  - http
paths:
  /results/results_by_class:
    post:
      tags:
        - results
      summary: Get all predcition for a particular class
      x-swagger-router-controller: SampleController
      description: ""
      operationId: getResultClass
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Class name to extract data
          required: false
          schema:
            $ref: "#/definitions/Book"
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Class"
        "400":
          description: Invalid ID supplied
        "404":
          description: Class not found
  "/results/get_results/{id}":
    get:
      tags:
        - results
      summary: Find results by ID
      description: Returns a single predicition
      operationId: getResultsById
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of Predcition to return
          required: true
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid ID supplied
        "404":
          description: Result not found
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: "http://petstore.swagger.io/api/oauth/dialog"
    flow: implicit
    scopes:
      "write:pets": modify pets in your account
      "read:pets": read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Order:
    properties:
      id:
        type: integer
        format: int64
      petId:
        type: integer
        format: int64
      quantity:
        type: integer
        format: int32
      shipDate:
        type: string
        format: date-time
      status:
        type: string
        description: Order Status
        enum:
          - placed
          - approved
          - delivered
      complete:
        type: boolean
    xml:
      name: Order
  Category:
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    xml:
      name: Category
  User:
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
      phone:
        type: string
      userStatus:
        type: integer
        format: int32
        description: User Status
    xml:
      name: User
  Tag:
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    xml:
      name: Tag
  Book:
    required:
      - title
      - author
    properties:
      title:
        type: string
        example: Python Basics
      author:
        type: string
        description: name of the author
        example: Author
  ApiResponse:
    type: object
    properties:
      index:
        type: integer
        format: int32
        description: id of the prediction
        example: 125
      Class:
        type: string
        description: prediction class
        example: Setosa
      Petal_Length:
        type: number
        format: float
        description: feature 1
        example: 5.1
      Petal_Width:
        type: number
        format: float
        description: feature 2
        example: 2.9
      Sepal_Length:
        type: number
        format: float
        description: feature 3
        example: 6.1
      Sepal_Width:
        type: number
        format: float
        description: feature 4
        example: 3.7
externalDocs:
  description: Find out more about Swagger
  url: "http://swagger.io"

